### ISSUE TITLE
Make something like `_gen_quimb_gates` public

### ISSUE THREAD

**Issue by garrison** [qiskit-community/qiskit-quimb#3]
In my experience with qiskit-quimb so far, I already want something with the functionality of `_gen_quimb_gates` to be public.  For instance, I believe this function is necessary to apply Qiskit gate(s) to an existing `CircuitMPS`, which can be done as `circuitmps.apply_gates(_gen_quimb_gates(gate, (q0, q1)))`.

It could really use a better name, though.

**Comment by kevinsung** [comment]
Of course, we can make it public. Any suggestions for the name?
